apiVersion: v2
name: jellyfin
description: The Free Software Media System
type: application
version: 0.2.6
appVersion: "release-10.10.5"
icon: "https://jellyfin.org/images/logo.svg"
dependencies:
- name: common
  version: 0.3.4
  repository: https://bubylou.github.io/Arr-Stack/
maintainers:
  - name: bubylou
    email: bubylou@pm.me
