environment:
  - name: TZ
    value: America/New_York
  - name: JELLYFIN_PublishedServerUrl
    value: 'https://jellyfin.bubylou.com'

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # traefik.ingress.kubernetes.io/router.middlewares: "sso-authelia@kubernetescrd"
  hosts:
    - host: test.bubylou.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
     - secretName: test-bubylou-tls
       hosts:
         - test.bubylou.com

volumes:
  - name: jellyfin-config
    persistentVolumeClaim:
      claimName: jellyfin-config
  - name: jellyfin-data
    persistentVolumeClaim:
      claimName: jellyfin-data
  - name: jellyfin-cache
    persistentVolumeClaim:
      claimName: jellyfin-cache
  - name: nfs-share
    nfs:
      server: nas01.bubylou.com
      path: /srv/share

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /config
    name: jellyfin-config
  - mountPath: /config/data
    name: jellyfin-data
  - mountPath: /config/cache
    name: jellyfin-cache
  - mountPath: /data/media/movies
    name: nfs-share
    subPath: Movies
  - mountPath: /data/media/tv
    name: nfs-share
    subPath: TV
