{{- include "common.deployment" . }}
          lifecycle:
            postStart:
              exec:
                command: [ "sh", "-c" ]
                args:
                  - |
                    mkdir -p /config/config
                    cp /tmp/qBittorrent.conf /config/config/qBittorrent.conf
                    chown hotio -R /config/config

           volumeMounts:
            - name: qbittorrent-data
              mountPath: /config
            - name: config
              mountPath: /tmp
      volumes:
        - name: qbittorrent-data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "app.fullname" . }}
            items:
              - key: config
                path: qBittorrent.conf
