{{- include "common.deployment" . }}
{{- if .Values.bootstrap.enabled }}
      initContainers:
        - name: sysctl
          image: busybox:1.37
          securityContext:
            privileged: true
          command:
            [
              "sh",
              "-c",
              "sysctl -w net.ipv4.conf.all.src_valid_mark=1 net.ipv6.conf.all.disable_ipv6=1"
            ]
{{- end }}
