{{- if .Values.discovery.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "app.fullname" . }}
{{- end }}
