{{- if .Values.discovery.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
secrets:
  - name: {{ include "app.fullname" . }}
{{- end }}
