{{- define "common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
{{- end -}}

{{- define "arr.secret" -}}
{{- include "common.secret" -}}
  api-key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}
