---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  config: |-
    verbose = {{ .Values.ldap.verbose }}
    # ldap_host = "0.0.0.0"
    ldap_port = {{ .Values.service.ldap.port }}
    # http_host = "0.0.0.0"
    http_port = {{ .Values.service.http.port }}
    http_url = {{ .Values.ingress.hosts | quote }}
    # jwt_secret = "REPLACE_WITH_RANDOM"
    ldap_base_dn = {{ .Values.ldap.base_dn | quote }}

    ldap_user_dn = {{ .Values.ldap.user_dn | quote }}
    ldap_user_email = {{ .Values.ldap.user_email | quote }}
    # ldap_user_pass = "REPLACE_WITH_PASSWORD"
    force_ldap_user_pass_reset = {{ .Values.ldap.force_user_pass_reset }}

    database_url = "sqlite:///data/users.db?mode=rwc"
    key_file = {{ .Values.ldap.key_file | quote }}
    # key_seed = "RanD0m STR1ng"

    ignored_user_attributes = {{ .Values.ldap.ignored_user_attributes }}
    ignored_group_attributes = {{ .Values.ldap.ignored_group_attributes }}

    [smtp_options]
    enable_password_reset = {{ .Values.ldap.smtp.enable_password_reset }}
    server = {{ .Values.ldap.smtp.server | quote }}
    port = {{ .Values.ldap.smtp.port }}
    smtp_encryption = {{ .Values.ldap.smtp.smtp_encryption | quote }}
    user = {{ .Values.ldap.smtp.user | quote }}
    password = {{ .Values.ldap.smtp.password | quote }}
    from = {{ .Values.ldap.smtp.from | quote }}
    reply_to = {{ .Values.ldap.smtp.reply_to | quote }}

    [ldaps_options]
    enabled = {{ .Values.ldap.ldaps.enabled }}
    port = {{ .Values.ldap.ldaps.port }}
    cert_file = {{ .Values.ldap.ldaps.cert_file | quote }}
    key_file = {{ .Values.ldap.ldaps.key_file | quote}}
