---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
immutable: true
data:
  LLDAP_JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_KEY_SEED: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_ADMIN_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
