{{- include "common.secret" . }}
  LLDAP_JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_KEY_SEED: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_ADMIN_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
