---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
immutable: true
data:
  LLDAP_JWT_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_KEY_SEED: {{ randAlphaNum 32 | b64enc | quote }}
  LLDAP_ADMIN_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
{{- if .Values.bootstrap.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-bootstrap
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
type: Opaque
stringData:
  groups: |-
    {{- range .Values.bootstrap.groups }}
    {
      "name": {{ . | quote }}
    }
    {{- end }}

  users: |-
    {
      "id": "readonly",
      "email": "readonly@localhost",
      "password": {{ randAlphaNum 64 | quote }},
      "groups": [
        "lldap_strict_readonly"
      ]
    }
    {
      "id": "password_manager",
      "email": "password_manager@localhost",
      "password": {{ randAlphaNum 64 | quote }},
      "groups": [
        "lldap_password_manager"
      ]
    }
    {
      "id": "admin",
      "email": "admin@localhost",
      "password": {{ randAlphaNum 64 | quote }},
      "groups": [
        "lldap_manager"
      ]
    }
    {{- range .Values.bootstrap.users }}
    {
      "id": {{ required "id/username required" .id | quote }},
      "email": {{ required "email required" .email | quote }},
      "password": {{ randAlphaNum 64 | quote }},
      "displayName": {{ default "" .displayName | quote }},
      "firstName": {{  default "" .firstName | quote }},
      "lastName": {{  default "" .lastName | quote }},
      "groups": {{ toPrettyJson .groups | nindent 8 }}
    }
    {{- end }}
{{- end }}
