# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLDAP_JWT_SECRET: {{ randAlphaNum 32 | quote }}
  LLDAP_KEY_SEED: {{ randAlphaNum 32 | quote }}
