apiVersion: v2
name: readarr
description: Book Manager and Automation (Sonarr for Ebooks)
type: application
version: 0.1.3
appVersion: "testing-0.3.32.2587"
icon: "https://readarr.com/img/logo.png"
dependencies:
- name: common
  version: 0.1.2
  repository: file://../common
maintainers:
  - name: bubylou
    email: bubylou@pm.me
