apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
