apiVersion: v2
name: qbittorrent
description: qBittorrent BitTorrent client
type: application
version: 0.2.1
appVersion: "release-4.6.7"
icon: "https://avatars.githubusercontent.com/u/2131270"
dependencies:
- name: common
  version: 0.3.4
  repository: https://bubylou.github.io/Arr-Stack
maintainers:
  - name: bubylou
    email: bubylou@pm.me
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added artifacthub.io annotations
  artifacthub.io/images: |
    - name: qbittorrent
      image: hotio/qbittorrent
  artifacthub.io/links: |
    - name: Helm Repo
      url: https://github.com/bubylou/arr-stack
