# Default values for qbittorrent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/hotio/qbittorrent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "release-4.6.7"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: []
  # - name: TZ
  #   value: Etc/Utc

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

bootstrap:
  enable: false

config:
  Application:
    FileLogger:
      Age: 1
      AgeType: 1
      Backup: true
      DeleteOld: true
      Enabled: true
      MaxSizeBytes: 66560
      Path: /app/qBittorrent/data/logs

  BitTorrent:
    Session:
      AddTorrentStopped: false
      DefaultSavePath: /data/downloads/complete
      DisableAutoTMMByDefault: false
      ExcludedFileNames: ""
      Port: 62239
      QueueingSystemEnabled: false
      SSLPort: 63588
      ShareLimitAction: Stop
      TempPath: /data/downloads/incomplete
      TempPathEnabled: true

  Core:
    AutoDeleteAddedTorrentFile: Never

  Meta:
    MigrationVersion: 8

  Preferences:
    General:
      Locale: en
    MailNotification:
      req_auth: true
    WebUI:
      AlternativeUIEnabled: true
      AuthSubnetWhitelist: 0.0.0.0/0
      AuthSubnetWhitelistEnabled: true
      HostHeaderValidation: false
      LocalHostAuth: false
      RootFolder: /app/vuetorrent
      Username: admin

  RSS:
    AutoDownloader:
      DownloadRepacks: true
      SmartEpisodeFilter: s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: qbittorrent-data
#   persistentVolumeClaim:
#     claimName: qbittorrent-data
# - name: nfs-nas01
#   nfs:
#     server: nas01.local
#     path: /srv/share

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: qbittorrent-config
#   mountPath: "/config"
# - name: nfs-nas01
#   mountPath: "/data/downloads"
#   subPath: Downloads

nodeSelector: {}

tolerations: []

affinity: {}
