{{- if .Values.bootstrap.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-bootstrap
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "app.fullname" . }}-bootstrap
      labels:
        {{- include "app.labels" . | nindent 4 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ include "app.fullname" . }}
          image: alpine/httpie
          command: ['/bootstrap/bootstrap.sh']
          env:
            - name: PROWLARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.fullname" . }}
                  key: api-key
                  optional: false
            - name: LIDARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lidarr
                  key: api-key
                  optional: true
            - name: RADARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: radarr
                  key: api-key
                  optional: true
            - name: READARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: readarr
                  key: api-key
                  optional: true
            - name: SONARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sonarr
                  key: api-key
                  optional: true
          volumeMounts:
            - name: bootstrap
              mountPath: /bootstrap/bootstrap.sh
              subPath: bootstrap.sh
      volumes:
        - name: bootstrap
          configMap:
            name: prowlarr-bootstrap
            defaultMode: 0555
            items:
              - key: bootstrap.sh
                path: bootstrap.sh
{{- end }}
