apiVersion: v2
name: unpackerr
description: Extracts downloads for other arr apps
type: application
version: 0.1.1
appVersion: "release-0.14.0"
icon: "https://unpackerr.zip/img/icon.png"
dependencies:
- name: common
  version: 0.1.0
  repository: file://../common
