# Default values for unpackerr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/hotio/unpackerr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "release-0.14.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env: []
  # - name: TZ
  #   value: Etc/Utc

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

lidarr:
  enabled: false
  url: "http://lidarr:8686"
  paths: ['/downloads']
  protocols: "torrent"
  timeout: "10s"
  delete_delay: "5m"
  delete_orig: false
  syncthing: false

radarr:
  enabled: false
  url: "http://radarr:7878"
  paths: ['/downloads']
  protocols: "torrent"
  timeout: "10s"
  delete_delay: "5m"
  delete_orig: false
  syncthing: false

readarr:
  enabled: false
  url: "http://readarr:8787"
  paths: ['/downloads']
  protocols: "torrent"
  timeout: "10s"
  delete_delay: "5m"
  delete_orig: false
  syncthing: false

sonarr:
  enabled: false
  url: "http://sonarr:8989"
  paths: ['/downloads']
  protocols: "torrent"
  timeout: "10s"
  delete_delay: "5m"
  delete_orig: false
  syncthing: false

config:
  debug: false
  quiet: false
  error_stderr: false
  activity: false
  log_queues: "1m"
  log_file: '/downloads/unpackerr.log'
  log_files: 10
  log_file_mb: 10
  interval: "2m"
  start_delay: "1m"
  retry_delay: "5m"
  max_retries: 3
  parallel: 1
  file_mode: "0644"
  dir_mode: "0755"

  webserver:
    metrics: false
    listen_addr: "0.0.0.0:5656"
    log_file: ''
    log_files: 10
    log_file_mb: 10
    ssl_cert_file: ''
    ssl_key_file: ''
    urlbase: "/"
    upstreams: []

  folders:
    interval: "0s"
    buffer: 20000

  folder:
    path: '/downloads/auto_extract'
    extract_path: ''
    delete_after: "10m"
    disable_recursion: false
    delete_files: false
    delete_original: false
    disable_log: false
    move_back: false
    extract_isos: false

  webhook:
    url: "https://notifiarr.com/api/v1/notification/unpackerr/api_key_from_notifiarr_com"
    name: ""
    silent: false
    events: [1, 4, 6]
    nickname: "Unpackerr"
    channel: ""
    exclude: ["readarr", "lidarr"]
    template_path: ''
    template: ""
    ignore_ssl: false
    timeout: "10s"
    content_type: "application/json"

  cmdhook:
    command: '/downloads/scripts/command.sh'
    name: ""
    shell: false
    silent: false
    events: [1, 4, 7]
    exclude: ["readarr", "lidarr"]
    timeout: "10s"

service:
  type: ClusterIP
  port: 5656

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: nfs-nas01
#   nfs:
#     server: nas01.local
#     path: /srv/share/Downloads

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: nfs-nas01
#   mountPath: "/data/downloads"

nodeSelector: {}

tolerations: []

affinity: {}
