---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unpackerr
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  config: |-
    {{- with .Values.config }}
    debug = {{ .debug }}
    quiet = {{ .quiet }}
    error_stderr = {{ .error_stderr }}
    activity = {{ .activity }}
    log_queues = {{ .log_queues | quote }}
    log_file = {{ .log_file | quote }}
    log_files = {{ .log_files }}
    log_file_mb = {{ .log_file_mb }}
    interval = {{ .interval | quote }}
    start_delay = {{ .start_delay | quote }}
    retry_delay = {{ .retry_delay | quote }}
    max_retries = {{ .max_retries }}
    parallel = {{ .parallel }}
    file_mode = {{ .file_mode | quote }}
    dir_mode = {{ .dir_mode | quote }}

    [webserver]
    metrics = {{ .webserver.metrics }}
    listen_addr = {{ .webserver.listen_addr | quote }}
    log_file = {{ .webserver.log_file | quote }}
    log_files = {{ .webserver.log_files }}
    log_file_mb = {{ .webserver.log_file_mb }}
    ssl_cert_file = {{ .webserver.ssl_cert_file | quote }}
    ssl_key_file = {{ .webserver.ssl_key_file | quote }}
    urlbase = {{ .webserver.urlbase | quote }}
    upstreams = {{ .webserver.upstreams }}

    [[folder]]
    path = {{ .folder.path | quote }}
    extract_path = {{ .folder.extract_path | quote }}
    delete_after = {{ .folder.delete_after | quote }}
    disable_recursion = {{ .folder.disable_recursion }}
    delete_files = {{ .folder.delete_files }}
    delete_original = {{ .folder.delete_original }}
    disable_log = {{ .folder.disable_log }}
    move_back = {{ .folder.move_back }}
    extract_isos = {{ .folder.extract_isos }}
    interval = {{ .folder.interval | quote }}
    buffer = {{ .folder.buffer }}

    [[webhook]]
    url = {{ .webhook.url | quote }}
    name = {{ .webhook.name | quote }}
    silent = {{ .webhook.silent }}
    events = {{ .webhook.events }}
    nickname = {{ .webhook.nickname | quote }}
    channel = {{ .webhook.channel | quote }}
    exclude = {{ .webhook.exclude }}
    template_path = {{ .webhook.template_path | quote }}
    template = {{ .webhook.template | quote }}
    ignore_ssl = {{ .webhook.ignore_ssl }}
    timeout = {{ .webhook.timeout | quote }}
    content_type = {{ .webhook.content_type | quote }}

    [[cmdhook]]
    command = {{ .cmdhook.command | quote }}
    name = {{ .cmdhook.name | quote }}
    shell = {{ .cmdhook.shell }}
    silent = {{ .cmdhook.silent }}
    events = {{ .cmdhook.events }}
    exclude = {{ .cmdhook.exclude }}
    timeout = {{ .cmdhook.timeout | quote }}
    {{- end }}

    {{ if .Values.lidarr.enabled }}
    [[lidarr]]
    url = {{ .Values.lidarr.url | quote }}
    api_key = "filepath:/secrets/lidarr"
    paths = {{ .Values.lidarr.paths | quote }}
    protocols = {{ .Values.lidarr.protocols | quote }}
    timeout = {{ .Values.lidarr.timeout | quote }}
    delete_delay = {{ .Values.lidarr.delete_delay | quote }}
    delete_orig = {{ .Values.lidarr.delete_orig }}
    syncthing = {{ .Values.lidarr.syncthing }}
    {{ end }}

    {{- if .Values.radarr.enabled }}
    [[radarr]]
    url = {{ .Values.radarr.url | quote }}
    api_key = "filepath:/secrets/radarr"
    paths = {{ .Values.radarr.paths }}
    protocols = {{ .Values.radarr.protocols | quote }}
    timeout = {{ .Values.radarr.timeout | quote }}
    delete_delay = {{ .Values.radarr.delete_delay | quote }}
    delete_orig = {{ .Values.radarr.delete_orig }}
    syncthing = {{ .Values.radarr.syncthing }}
    {{ end }}

    {{- if .Values.readarr.enabled }}
    [[readarr]]
    url = {{ .Values.readarr.url | quote }}
    api_key = "filepath:/secrets/readarr"
    paths = {{ .Values.readarr.paths }}
    protocols = {{ .Values.readarr.protocols | quote }}
    timeout = {{ .Values.readarr.timeout | quote }}
    delete_delay = {{ .Values.readarr.delete_delay | quote }}
    delete_orig = {{ .Values.readarr.delete_orig }}
    syncthing = {{ .Values.readarr.syncthing }}
    {{ end }}

    {{- if .Values.sonarr.enabled }}
    [[sonarr]]
    url = {{ .Values.sonarr.url | quote }}
    api_key = "filepath:/secrets/sonarr"
    paths = {{ .Values.sonarr.paths }}
    protocols = {{ .Values.sonarr.protocols | quote }}
    timeout = {{ .Values.sonarr.timeout | quote }}
    delete_delay = {{ .Values.sonarr.delete_delay | quote }}
    delete_orig = {{ .Values.sonarr.delete_orig }}
    syncthing = {{ .Values.sonarr.syncthing }}
    {{ end }}
