apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: UN_LIDARR_0_URL
              value: "http://lidarr.{{ .Release.Namespace }}.svc:8686"
            - name: UN_LIDARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lidarr 
                  key: api-key
                  optional: true
            - name: UN_RADARR_0_URL
              value: "http://radarr.{{ .Release.Namespace }}.svc:7878"
            - name: UN_RADARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: radarr
                  key: api-key
                  optional: true
            - name: UN_READARR_0_URL
              value: "http://readarr.{{ .Release.Namespace }}.svc:8787"
            - name: UN_READARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: readarr
                  key: api-key
                  optional: true
            - name: UN_SONARR_0_URL
              value: "http://sonarr.{{ .Release.Namespace }}.svc:8989"
            - name: UN_SONARR_0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sonarr
                  key: api-key
                  optional: true
          {{- with $env := .Values.env }}{{ toYaml $env | nindent 12 }}{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
